services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_BASE_URL=https://albums-ickh.onrender.com # use http://localhost:8080 for local use

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/momentos
     - SPRING_DATASOURCE_USERNAME=your-username
     - SPRING_DATASOURCE_PASSWORD=your-password

