services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend/.env:/app/.env 
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dpg-ct4oh8dumphs73e742jg-a.oregon-postgres.render.com:5432/momentos
      - SPRING_DATASOURCE_USERNAME=momentos_user
      - SPRING_DATASOURCE_PASSWORD=9bJOxiJ38kgTD9bKyN7oJ40JfzwXXABu

